### ISSUE TITLE
Default timeout issue

### ISSUE THREAD

**Issue by MoltoDev** [osrseye/rseye-connector#4]
I would like an option to change the timeout

Because my server is slow, sometimes it can take 60 seconds for a request to come through, but I think the default timeout for this rseye connector is lower

Can we add an option to add how long until a connection times out?

**Comment by BasketBandit** [comment]
Default timeout for OkHttp (library used by the plugin & runeline) is 10 seconds. My recollection (will need to double check) is that the http client is created by runelite itself and we merely use that object. 
This means that although the library does support what you want, whether or not we can apply a timeout retrospectively at runtime I'm not sure. 

Will check in the morning.

**Comment by MoltoDev** [comment]
Thanks bro, if there is a way to change the timeout it would solve all my problems, as my server is accepting a timeout for up to 5 minutes
