### ISSUE TITLE
Option to constantly send inventory and bank

### ISSUE THREAD

**Issue by MoltoDev** [osrseye/rseye-connector#5]
Related to my timeout issue, is it possible to constantly send the bank and inevntory update every x miliseconds?

**Comment by BasketBandit** [comment]
The plugin works based on events published by runelite - this means that we don't actually know what's in a player's inventory until they interact with it (drop, pickup, rearrange) and an event is fired. This is the same with the bank. 
My suggestion would be to cache the contents of the inventory/bank on your side once the event has fired. 
Sending the same update every few milliseconds doesn't provide you with any additional information from what was sent the first time.
