### ISSUE TITLE
Player caching issue

### ISSUE THREAD

**Issue by MoltoDev** [osrseye/rseye-connector#6]
You can ignore my other 2 issues, as I found the actual issue causing the inventory and bank to show wrong, I will explain it as best I can

It was not related to timeout at all, but after extensive debugging I found the issue:

In ConnectorPlugin class the 'player' variable gets updated too slowly for updates to be sent

for example first login on client launch

- logs in
game state changes
login update doesn't get posted due to player being null
other updates don't get posted due to player being null
next tick, player is set, updates are posted fine but the first updates are missed

or another example if we switch account

- old account logs out
hasTicked is set to false BUT player remains as the previous character
- new account logs in
game state changes
login update gets posted with old username
other updates get posted with old username
next tick, player is set, updates are posted fine but the first updates are attributed to the wrong username

would be easier to fix this by just not caching the player and instead each time getting it from client.getLocalPlayer() whenever needed
and whenever hasTicked is set to false, do the resets for questStates etc there rather than in onGameTick instead of using hasTicked variable

I hope you can get this plugin sorted/updated ASAP it would be much appreciated as I rely on this plugin a lot

**Comment by BasketBandit** [comment]
I reckon this case could be avoided just by also setting the player to null when "hasTicked" is also set to false, preventing events slipping through due to the player now being stale.
> old account logs out
hasTicked is set to false BUT player remains as the previous character
new account logs in
game state changes
login update gets posted with old username
other updates get posted with old username
next tick, player is set, updates are posted fine but the first updates are attributed to the wrong username

I think I get what you're putting down, I guess I just assumed that setting that value there and then waiting for the next tick to update the player would be fine but maybe not. Will have to test it out.
>In ConnectorPlugin class the 'player' variable gets updated too slowly for updates to be sent

**Comment by MoltoDev** [comment]
Well basically the inventory update is firing for the previous account making the inventory incorrect

1. I login on username "a"
2. No event gets fired for username "a"
3. I login to username "b"
4. An inventory update gets fired with the username "a"

Is there any way that you could fix this or add an option to wait until the LOGGED_IN event is happening and then fire the event

At the end of the day doing this would cause maybe a 600ms delay or something but solve a very big issue

The system currently can't work out everyones inventory correctly with this bug

I'd really appreciate it if you could get this resolved, it's been causing me a nightmare over the past week

**Comment by BasketBandit** [comment]
> Well basically the inventory update is firing for the previous account making the inventory incorrect
> 
> 1. I login on username "a"
> 2. No event gets fired for username "a"
> 3. I login to username "b"
> 4. An inventory update gets fired with the username "a"
> 
> Is there any way that you could fix this or add an option to wait until the LOGGED_IN event is happening and then fire the event
> 
> At the end of the day doing this would cause maybe a 600ms delay or something but solve a very big issue
> 
> The system currently can't work out everyones inventory correctly with this bug
> 
> I'd really appreciate it if you could get this resolved, it's been causing me a nightmare over the past week

Yep this problem I can fix, that's not an issue - its the problem with the first event not firing that's the tricky bit. However even if I pushed an update today its upto the runelite maintainers to merge the code into pluginhub

**Comment by BasketBandit** [comment]
> When setting the player in onGameTick set the username to all the updates

I can see an edge case here where the player logs out and the player variable is unset before its sent causing it to stick in the queue until you log in again (potentially with another account) OR you login, its "null" but then you don't continue logging in and instead switch accounts. 

I'll push an update here soon and review.

**Comment by MoltoDev** [comment]
You could just clear the queue on logout would probably be fine, and as for the other edge cases they seem very unlikely to happen, it would be nearly impossible to logout and switch accounts for that issue to happen, but I think cleared the queue on logout would solve these possible issues even if they are unlikely to happen

**Comment by BasketBandit** [comment]
I've pushed to a new branch here: https://github.com/osrseye/rseye-connector/compare/master...patch/fix-player-data-mismatch
if you're familiar with the process you can pull it down and test locally if you want but I think this should cover at first glance

**Comment by MoltoDev** [comment]
I just tested it and it works flawlessly now, it took me quite a while to compile to test it but yeah it's all working now!

How long do you think it will take for the runelite mods to update this on the plugin hub?

**Comment by BasketBandit** [comment]
its hard to say but once I've made the merge request I'll link it here so you can keep tabs

**Comment by BasketBandit** [comment]
https://github.com/runelite/plugin-hub/pull/4825

**Comment by MoltoDev** [comment]
Thanks so much I appreciate it!
