### ISSUE TITLE
Plugin broken after skull update

### ISSUE THREAD

**Issue by MantasJur** [osrseye/rseye-connector#9]
Hi! Skull icon update broke the plugin. Commit that is probably responsible for the plugin not working:

https://github.com/runelite/runelite/commit/4740ea57da059bda7a601f5090d70d4b9105c535

**Comment by BasketBandit** [comment]
Hi, thanks a lot for contributing! I've seen the PR and will test quickly when I get home from work. So should be within the next 6 hours or so.

**Comment by BasketBandit** [comment]
Bit delayed, apologies. You can track the PR on plugin hub here - https://github.com/runelite/plugin-hub/pull/6634, once this is merged it'll be live.
